# Generated by Django 3.2.8 on 2021-10-15 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='publisher',
        ),
        migrations.AddField(
            model_name='blog',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
